main: com.gmail.artemis.the.gr8.playerstats.Main
name: PlayerStats
version: 1.0
api-version: 1.18
description: adds commands to view player statistics in chat
author: Artemis_the_gr8
commands:
  statistic:
    aliases:
      - stat
      - stats
    description: general statistic command
    usage: "§7[§6PlayerStats§7]
    /statistic <statistic-name> [item-, material- or entity-name] {top | player | me} [player-name]"
    permission: playerstats.stat
  statisticreload:
    aliases:
      - statreload
      - statsreload
    description: reloads the config
    usage: "§a/statisticreload"
    permission: playerstats.reload
permissions:
  playerstats.stat:
    description: lowest permission level
    default: op
  playerstats.reload:
    description: allows config and scoreboard related things?
    default: op